version: '3.7'

services:
  client:
    container_name: pf-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./client:/home/node/app/client
      - /home/node/app/client/node_modules
    depends_on:
      - server
      - mongo
    stdin_open: true
  server:
    container_name: pf-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - ./server:/home/node/app/server
      - /home/node/app/server/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/pb
      - PORT=8080
      - NODE_ENV=development
    env_file: ./server/.env
  mongo:
    container_name: pf-mongo
    image: mongo
    ports:
      - '27017:27017'
